package factory;

public enum GearType {

    WEAPON_AK308(GearSlot.WEAPON),
    WEAPON_RSSAS(GearSlot.WEAPON),
    WEAPON_TKPD(GearSlot.WEAPON),
    WEAPON_MP7A1(GearSlot.WEAPON),
    WEAPON_NL545(GearSlot.WEAPON),
    WEAPON_MPX(GearSlot.WEAPON),
    WEAPON_AVT_40(GearSlot.WEAPON),

    HELMET_NONE(GearSlot.HELMET),
    HELMET_FAST_MT(GearSlot.HELMET),
    HELMET_ALTYN(GearSlot.HELMET),
    HELMET_ULACH(GearSlot.HELMET),
    HELMET_LSHZ_2DTM(GearSlot.HELMET),
    HELMET_ZSH_1_2M(GearSlot.HELMET),
    HELMET_KIVER_M(GearSlot.HELMET),

    ARMOR_PACA(GearSlot.ARMOR),
    ARMOR_6B2(GearSlot.ARMOR),
    ARMOR_6B13(GearSlot.ARMOR),
    ARMOR_KORUND(GearSlot.ARMOR),
    ARMOR_GZHEL(GearSlot.ARMOR),
    ARMOR_SLICK(GearSlot.ARMOR),
    ARMOR_FORT_REDUT_M(GearSlot.ARMOR),

    RIG_BANK_ROBBER(GearSlot.RIG),
    RIG_MK3(GearSlot.RIG),
    RIG_AVS(GearSlot.RIG),
    RIG_BLACKROCK(GearSlot.RIG),
    RIG_CSA(GearSlot.RIG),
    RIG_SMR(GearSlot.RIG),
    RIG_TV_106_107(GearSlot.RIG),

    ARMORED_RIG_TV110(GearSlot.ARMORED_RIG),
    ARMORED_RIG_AACPC(GearSlot.ARMORED_RIG),
    ARMORED_RIG_6B3TM(GearSlot.ARMORED_RIG),
    ARMORED_RIG_6B5_15(GearSlot.ARMORED_RIG),
    ARMORED_RIG_MMCA(GearSlot.ARMORED_RIG),
    ARMORED_RIG_TACTEC(GearSlot.ARMORED_RIG),
    ARMORED_RIG_CPC_MOD2(GearSlot.ARMORED_RIG),

    HEADSET_NONE(GearSlot.HEADSET),
    HEADSET_GSSH_01(GearSlot.HEADSET),
    HEADSET_PELTOR_COMTAC_2(GearSlot.HEADSET),
    HEADSET_PELTOR_COMTAC_4(GearSlot.HEADSET),
    HEADSET_SORDIN(GearSlot.HEADSET),
    HEADSET_RAZOR(GearSlot.HEADSET),
    HEADSET_XCEL(GearSlot.HEADSET),

    FACECOVER_NONE(GearSlot.FACECOVER),
    FACECOVER_BALACLAVA(GearSlot.FACECOVER),
    FACECOVER_HALFMASK(GearSlot.FACECOVER),
    FACECOVER_SHEMAGH(GearSlot.FACECOVER),
    FACECOVER_BANDANA(GearSlot.FACECOVER),
    FACECOVER_GHOST_BALACLAVA(GearSlot.FACECOVER),
    FACECOVER_NEOPRENE_MASK(GearSlot.FACECOVER),

    BACKPACK_NONE(GearSlot.BACKPACK),
    BACKPACK_BERKUT(GearSlot.BACKPACK),
    BACKPACK_DAY_PACK(GearSlot.BACKPACK),
    BACKPACK_SCAV_BP(GearSlot.BACKPACK),
    BACKPACK_TRIZIP(GearSlot.BACKPACK),
    BACKPACK_PILGRIM(GearSlot.BACKPACK),
    BACKPACK_ATTACK2(GearSlot.BACKPACK);

    private final GearSlot slot;

    GearType(GearSlot slot) {
        this.slot = slot;
    }

    public GearSlot slot() {
        return slot;
    }
}
